version: '3.8'
services:
  dev-db:
    image: postgres:14.1-alpine
    restart: "no"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=initial_db
    stop_signal: SIGTERM
    ports:
      - '5434:5432'
    volumes:
      - dev-db-data:/var/lib/postgresql/data
volumes:
  dev-db-data:
    driver: local
