openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:3333'
paths:
  /lastLoginForUser:
    get:
      summary: Get last login for user
      description: Get last login for user
      operationId: getLastLoginForUser
#      parameters:
#        - name: userId
#          in: query
#          description: User id
#          required: true
#          schema:
#            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  lastLogin:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
